@startuml
'https://plantuml.com/class-diagram

class Solution42
{
    Scanner reader
    List<String> userData
    +main()
}
class DataParser
{
    +DataParser(List<String> userData, Scanner reader)
    +getUserData()
    +printUserData()
    +parseUserData()
}
Solution42 <|-- DataParser
@enduml