@startuml
'https://plantuml.com/class-diagram

class Solution46
{
    List<WordCounter> wordCounterList
    Scanner reader

    main()
    scanFile(reader, List<WordCounter> wordCounterList)
    printWordsInOrder(List<WordCounter> wordCounterList)
    printWord(WordCounter highestWord)
}
class WordCounter
{
    String uniqueWord
    int wordCount
    WordCounter(String uniqueWord, int wordCount)
}
Solution46 <|-- WordCounter

@enduml