@startuml
'https://plantuml.com/class-diagram

class ArrayList {
Scanner reader
ArrayList<String> names

getUnsortedNames(reader, ArrayList<String> names)
sortNames(names)
printNamesToFile(names)
}

@enduml