@startuml
'https://plantuml.com/class-diagram

class Solution44
{
    -Scanner reader
    Product[] products

    main()
    -loopProductSearch()
}
class Product
{
    String name;
    double price;
    int quantity;

    +searchProducts()
}
Solution44 <|-- Product
@enduml